### ISSUE TITLE
env 是个啥？

### ISSUE THREAD

**Issue by ijackwu** [MissMyCat/aliyun-sms-sdk#1]
Config.php evn 抛错了

**Comment by MissMyCat** [comment]
这个项目是给 [主项目](https://github.com/MissMyCat/aliyun-sms) 提供依赖，并没有其他的地方对本项目存在引用。如果是上面那个阿里云短信服务出现了问题，你可以在[这儿](https://github.com/MissMyCat/aliyun-sms/issues) 提出问题，我再给你解答。
.env 文件在是laravel项目配置环境变量的问题，初始化的时候并不存在。
你可以尝试
`
cp .env.example .env
`
这个命令创建.env文件

**Comment by ijackwu** [comment]
能去掉吗？yii也想用这个扩展。现在解决方案是俺，特别定义一个空方法 env

**Comment by MissMyCat** [comment]
@ijackwu 我明白你的意思了，就是希望去掉laravel 依赖，能够让其他的框架也能更好地使用这个sdk是吧。
明确答复你，可以去掉。大概在今晚更新一个版本，如果有事儿耽误了，下周一之前绝对搞定。

**Comment by ijackwu** [comment]
感谢！

**Comment by MissMyCat** [comment]
@ijackwu 我本地测试已经没有问题，你可以在[这儿](https://github.com/MissMyCat/aliyun-sms)看下介绍的使用方法，如果还有问题，去那个项目里面提，我给你解决。

**Comment by ijackwu** [comment]
@MissMyCat   感谢！！！
